const data = Object.freeze({
    appTitle: "Circle Generator",
    minWidth: 1,
    maxWidth: 257,
    minThickness: 1,
    maxThickness: 16,
    minCoord: -30000000,
    maxCoord: 30000000,
    minY: -64,
    maxY: 320,
    defaultWidth: 21,
    defaultThickness: 1,
    defaultCenter: Object.freeze({
        x: 0,
        y: 64,
        z: 0,
    }),
    zoom: Object.freeze({
        min: 0.25,
        max: 96,
        default: 30,
        sliderMin: 0,
        sliderMax: 1000,
        sliderStep: 1,
        wheelSensitivity: 0.0018,
    }),
    blocks: Object.freeze([
        Object.freeze({ id: "stone", label: "Stone", color: "#9fa3a8" }),
        Object.freeze({ id: "deepslate", label: "Deepslate", color: "#545a64" }),
        Object.freeze({ id: "oak_planks", label: "Oak Planks", color: "#be9f68" }),
        Object.freeze({ id: "spruce_planks", label: "Spruce Planks", color: "#8e6a44" }),
        Object.freeze({ id: "copper", label: "Copper", color: "#bf7a52" }),
        Object.freeze({ id: "prismarine", label: "Prismarine", color: "#63a592" }),
        Object.freeze({ id: "quartz", label: "Quartz", color: "#ece6df" }),
        Object.freeze({ id: "blackstone", label: "Blackstone", color: "#3a353a" }),
    ]),
    defaultBlockId: "stone",
});
